guardian/fulfilment-lambdas

build-tc.sh, cloudformation/cloudformation.yaml, package.json, riff-raff.yaml, src/exporter.js, yarn.lock
Adds the exporter and should allow an end to end deployment.
=> Add exporter and fix deployment.

cloudformation/cloudformation.yaml, riff-raff.yaml
=> Update bucket used for deployment.

package.json, src/config.js, src/fetcher.js, test/exporter.json, test/fetcher.json
=> Update config and allow exporter to be run locally

cloudformation/cloudformation.yaml
also added reminder to fix the state machine name issue.
=> fixed dist bucket in cloudformation

package.json, src/NamedError.js, src/config.js, src/exporter.js, src/fetcher.js, src/querier.js, test/exporter.json, test/fetcher.json, test/querier.json, yarn.lock
=> Use standardjs for linting 

cloudformation/cloudformation.yaml, riff-raff.yaml
I'd like to deploy this lambda to code, check all the S3 setting and then set up and run on prod.
=> Add salesforce downloader lambda to riffraff.

cloudformation/cloudformation.yaml
Listobjects needs to be granted on the bucket, not individual resources in bucket.
=> fix cloudformation for salesforce downloading

README.md
@pvighi @AWare @jacobwinch @lmath first try, please help! feel free to edit directly in this branch.
=> new readme with skeleton information

src/salesforce_downloader.js
Previously was using a hardcoded folder id, which limited this to CODE
=> Fetch folder id from salesforce.

src/fetcher.js, test/fetcher.json
Replace promise chain with async/await in the fetcher.
=> Fetcher async await

package.json, src/comparator.js
A lambda which compares our files to those in salesforce. *
*Only runs on the first mutually present file that hasn't been compared yet.
=> Comparator

cloudformation/cloudformation.yaml, src/comparator.js
Add comparator to cf and remove some debug log entries.
=> Deploy comparator.

src/comparator.js
An embarrassing error. 
@jacobwinch
=> Compare the right filenames.

.gitignore, cloudformation/cloudformation.yaml, package.json, yarn.lock
But only when we need to, should we do all prod/code stuff using these scripts?
=> Add a cloudform yarn script to generate the prod/code cloudformation

cloudformation/cloudformation.yaml
If any state fails for any reason retry al least 3 times before failing the whole state machine execution
=> Added retry to all states

src/exporter.js, src/querier.js
i think we still need to backfill for existing subs
=> added delivery instructions to fulfilment file

package.json, src/exporter.js, src/lib/formatters.js, test/postcode.js, yarn.lock
Format postcodes as requested for delivery and test this.
=> Format postcodes

src/comparator.js
Now it's a bit more reliable, compare all downloaded and generated fulfilments.
=> Run comparator against all files eligable

src/exporter.js, src/querier.js
https://trello.com/c/I6uJHJAF/180-add-delivery-instructions-to-fulfilment-file
=> Fetch delivery instructions from account field.

src/fetcher.js, src/lib/storage.js
=> use the storage module from fetcher, remove some duplication

__tests__/exporter.js, src/comparator.js, src/exporter.js, src/fetcher.js, src/lib/salesforceAuthenticator.js, src/querier.js, src/salesforce_downloader.js, src/salesforce_uploader.js
To allow us to pass things to later lamdas, I'm passing through the input to output in all of the lamdas.
If we think this is a good move, then I'll fix the tests.
=> Makes all lamdas pass through their inputs.

src/comparator.js
Allow all forms of valid phone number, and ignore the delivery quantity field as we don't use it.
=> Tweaks to comparator to reduce noise.

__tests__/querier.js, cloudformation/cloudformation.yaml, src/querier.js
- added the option to trigger the state mache with an input parameter "deliverydateDaysFromNow" instead of a specific day
- added a cloudwatch rule to trigger fulfilment at 11:00 GMT mon-fri, This rule will trigger 4 executions for the following 4 days  
@AWare @paulbrown1982
=> Cloudwatch trigger

src/comparator.js
Reverts guardian/fulfilment-lambdas#37
=> Revert "Tweaks to comparator to reduce noise."

__tests__/salesforce_uploader.js, src/lib/storage.js, src/salesforce_uploader.js
every time files are requested from salesforce, keep a copy of what was uploaded in an "uploaded" folder in our S3 bucket
@paulbrown1982 @AWare
=> copy uploaded files to uploaded folder

src/comparator.js, src/exporter.js, src/lib/filenames.js
1. puts all of the logic that deals with what file has what name in `lib/filenames.js`
2. cuts down the noise when comparing
3. tells you which row has bad data
=> second attempt at comparitor changes

src/exporter.js
=> Fix the exporter by renaming the import.

src/comparator.js
Remove sent date from each output and bring to start of file.
Show the sent date only once.,
=> Display sub number by each difference, and only show sent date once.

src/comparator.js
I've made a type alias for `{[string]:Array<customer>}` and moved the date checker into its' own function.
Bonus: teamcity now feeds back build status thanks to @rtyley
=> Update the comparator so it's a bit nicer and the flow check works.

__tests__/querier.js, src/fetcher.js, src/lib/Zuora.js, src/querier.js
This is just a copy/paste job to prepare for the new pipelines.
=> Move the Zuora code into its' own class and refactor to use that.

__tests__/exporter.js, package.json, src/exporter.js, src/fetcher.js, src/lib/storage.js, yarn.lock
Changing api form streams to promises.
This supports the weekly fulfilment pr.
=> Use promises to upload to s3

src/fetcher.js
Wasn't returning right data for exporter.
=> Fix upload type.

cloudformation/cloudformation.yaml
SFDownloaderScheduledRule -> SFDownloadScheduledRule
=> fix typo in cloudformation

__tests__/resources/input/homedelivery/querier.json, src/homedelivery/query.js
Replaces the query for home delivery with the old one, will make pr comments from #53 in separate pr
=> revert hd query to old query

src/homedelivery/query.js
Re-add these changes to hd query now it's working again.
=> Add title and change delivery instructions.

src/comparator.js
I hadn't changed the log comparison so that it removed dates using .formatDate() on Filename, and instead used the raw moment.
Oops.
Also using .size, as Map has .size and not .length (and some other Map fixes)
Bonus:
Cleans up output using .formatDate()
Removes some deps that are superfluous.
=> Fixes comparator (Don't recheck every file)

cloudformation/cloudformation.yaml, src/comparator.js, src/lib/Zuora.js, src/lib/config.js, src/lib/states.js, src/weekly/WeeklyExporter.js, src/weekly/export.js, src/weekly/query.js
Mirror existing weekly files.
Todo:
=> handle weekly fulfilment for CA/US/AUS

src/lib/config.js, src/weekly/export.js
=> Fix typo in weekly conf.

src/comparator.js
Make the comparator a little safer with differently formatted data.
=> Refactor comparator so it works with weekly output.

src/lib/Zuora.js, src/weekly/query.js
This query somewhat improves on our low numbers for this fulfilment. 
Would like to merge and then do a few runs and see how close we are now.
=> Weekly query autorenew

src/homedelivery/query.js
tweaked HD query to excluded cancelled subs that end the same day of the delivery
@paulbrown1982 @AWare
=> fixed HD query for special cancellation case

src/weekly/query.js
https://github.com/guardian/fulfilment-lambdas/pull/71 but for weekly 
@pvighi
=> Update query to not fulfil on cancellation date.

src/comparator.js
Fix comparator output to avoid getting "Unidentified change" lines
@AWare
=> fix comparator output

src/lib/storage.js
=> add encryption to copy operation

__tests__/weekly/query.js, cloudformation/cloudformation.yaml, src/querier.js, src/weekly/query.js
- added extra parameters to weekly querier to generate fulfilment files every day.
- Changed cloudwatch rule to generate weekly file every day
- refactored cloudwatch rule for home delivery to make the cloudformation template more readable 
@AWare @paulbrown1982 @jacobwinch @johnduffell
=> Weekly trigger

riff-raff.yaml
added the new lambda created in [my previous pr](https://github.com/guardian/fulfilment-lambdas/pull/89) to riff-raff.yaml so that it gets updated when the app is deployed
@AWare @paulbrown1982 @johnduffell @lmath
=> forgot to add the new lambda to riffraff.yaml in my last pr

cloudformation/cloudformation.yaml
=> added execution failed alarm for fulfilment lambdas

cloudformation/cloudformation.yaml
the old bucket will be deleted as it is no longer in use
=> remove permissions to old unencrypted private bucket

__tests__/lib/formatters.js, package.json, src/homedelivery/export.js, src/lib/formatters.js, src/weekly/WeeklyExporter.js, yarn.lock
- Capture with tests current csv output behaviour for Salesforce csv reader.
- This PR should contain no behavioural changes.
- Related Salesforce PR: [Clarify with tests current behaviour of CsvReader regarding quotes and commas #333 ](https://github.com/guardian/salesforce/pull/333)
- This is in preparation for potential refactoring to keep service layer and salesforce CSV readers in sync.
Tested with CODE step function confirming no changes to CSV files before and after. Files used
- 2021-01-27_HOME_DELIVERY.csv
- 2021-02-05_WEEKLY.csv
Test in CODE confirmed no changes to format by this PR.
=> Test current output csv format for salesforce csv reader

src/homedelivery/query.js, src/lib/HolidayCreditQuery.js, src/weekly/query.js
HD and GW use the same query for creating holiday suspension files.
=> Factor out common Holiday Credit query for HD and GW

src/weekly/query.js
Reverts guardian/fulfilment-lambdas#165
I'll submit another PR as this doesn't take account of cancellations pending.
=> Revert "Don't fulfil cancelled gift GW subs"

.github/workflows/snyk.yml
Adding Snyk github action to the project
=> Adding snyk GHA

package.json, yarn.lock
Upgrading dependencies using yarn
=> Upgrading dependencies

src/lib/salesforceAuthenticator.js
Version 20 is about to be decommissioned so updating to latest available version.
=> Bump Salesforce API to latest version

README.md
This morning's learning huddle suggested a couple of links might be useful.
=> Add some notes that came out of learning huddle
