guardian/fulfilment-lambdas

- src/querier.js
Since echo legacy subs are modelled as free days, we have to make sure that we don't fulfil them.  However it is not sensible to prevent people from having free subs in general, so this PR restricts the exclude free condition to echo legacy only.
I've added the frontend id in UAT and tested with some subs, and it seems to work, but we'll need to add the id in prod before we can fulfil. (if we forget, this will cause us to fulfil echo legacy subs every day of the week!!)
@AWare @pvighi @jacobwinch
> only exclude free days if it's an echo legacy plan

- src/querier.js
We were using lower case to parse the date, which cause moment to just fall back to today's date.  This meant we always tried to fulfil as if it were tuesday if it were a tuesday when the fulfilment was run, rather than using the given date to work out the day of the week.
@pvighi @AWare
> use caps to parse date

- src/querier.js
If a suspension rate plan has been removed, we shouldn't take it into account when fulfilling.  This fixes most of the duplicates, however there is one that really does have a duplicate holiday suspension for some reason.
@pvighi @AWare @jacobwinch
> ignore removed suspensions

- src/comparator.js
- src/lib/QuoteRemover.js
Remove quotes so we can check every sf fulfilment without hand fixing it.
> Remove quotes from inside fields in the sf fulfilment files for comparison

- cloudformation/cloudformation.yaml
- src/checker.js
- create the lambda log group explicity in the cloudformation template so that we can reference it from the log filter. (otherwise it's created the first time the lambda runs )
- fix the max age for fulfilment files in the check. If we assume this checking the fulfilment files for the next day and it will run after the fulfilment state machine then files will tipically be 0 days old except sundays and mondays.
@paulbrown1982 @AWare @jacobwinch
> fixes to checker

- __tests__/salesforce_uploader.js
- src/salesforce_uploader.js
added the last modified date for each file in the api response.
It's a very simple change and it would allow us to let the caller know how old the file is.
We can use this as an extra check to make sure the files are uploaded to sf after the fulfilment process has executed successfully.
sample response : 
```
{
"message": "ok",
"files": [
{
"name": "HOME_DELIVERY_Tuesday_25_07_2017.csv",
"id": "015g0000001FmvFAAS",
"lastModified": "2017-07-24"
},
{
"name": "HOME_DELIVERY_Wednesday_26_07_2017.csv",
"id": "015g0000001FmvPAAS",
"lastModified": "2017-07-25"
},
{
"name": "HOME_DELIVERY_Thursday_27_07_2017.csv",
"id": "015g0000001FmvKAAS",
"lastModified": "2017-07-26"
},
{
"name": "HOME_DELIVERY_Friday_28_07_2017.csv",
"id": "015g0000001FmvAAAS",
"lastModified": "2017-07-26"
}
]
}
```
@AWare …
> return last modified date on salesforce update api call

- cloudformation/cloudformation.yaml
The apoi allows to request upload for up to 5 days into the  future but the scheduled task was generating only 4.
@AWare
> generate fulfilment for 5 days 

- cloudformation/cloudformation.yaml
I don't know why either.
Before, the MetricFilter appeared as a thing that the CloudFormation stack had created, but could not be described by any of the AWS tools.
> Renaming the filter makes it reappear in CODE.

- cloudformation/cloudformation.yaml
- src/comparator.js
Same as
https://github.com/guardian/fulfilment-lambdas/pull/48
Add the downloader and comparator to the daily run, and recheck the future dated fulfilments.
We might want to run these at a different time, and I need to deploy the cloudformation on CODE
> Nightly download

- cloudformation/cloudformation.yaml
This fixes (in CODE) triggering the comparator lambda. 
The downloader is quite happy to run with the wrong policy- but is also fixed.
> Point lambda runner rule policies at the correct rules.

- src/lib/storage.js
- Importing a default export without {}'s
- Referencing a key that exists instead of doesn't.*
*I honestly don't know why the returned object had key and Key as fields, but everything else is uppercase.
> Some fixes to storage.js

- __tests__/resources/CODE/zuoraExport/Subscriptions_2017-07-06.csv
- __tests__/resources/expected/2017-07-06_HOME_DELIVERY.csv
- src/homedelivery/export.js
looking at the latest comparator output (2017-09-14_HOME_DELIVERY.log) I realized that a couple of customers first names were blank in the salesforce fulfilment and a single dot '.' in the file generated here.
The salesforce fulfilment is just removing names that are just a dot:
https://github.com/guardian/GNMTouchpoint/blob/129e50f89458d8054eb551fa15cc56dfe0d544c6/src/classes/FulfilmentBuilderUtil.cls#L98
So this PR is just replicating this.
@AWare @paulbrown1982
> replace dots with empty strings for first names in home delivery

- src/weekly/export.js
- src/weekly/query.js
This drops the number of subscription level differences from ~300 to ~100. 
This should drop when the next synchronised run of both fulfilments happens.
> Change the weekly query and add a filter to the exporter.

- cloudformation/cloudformation.yaml
We noticed that on Fridays the Home Delivery fulfiment file is often requested before our fulfilment lambdas run.
This would cause EDG to receive the fulfiment file generated the day before.
This PR changes the scheduling rule so that the fulfilment process runs earlier in the morning.
Expected consequences of this PR:
- EDG should always get fulfilment files generated on the same day they request it
- The comparator output for the rest of the days of the week will show more differences since there will be a couple of hours more between the generation of both files
@paulbrown1982 @johnduffell @lmath @AWare
> trigger fulfilment earlier

- cloudformation/cloudformation.yaml
pretty much the same as guardian/fulfilment-lambdas/pull/76.
I got confused by AWS using GMT and BST on different places and not telling you which time zone it's using.
9 GMT was not early enough while we are on BST, changed to 7 GMT just to be sure.
@paulbrown1982 @AWare @johnduffell @lmath
> change fulfilment trigger to 7 gmt

- src/homedelivery/query.js
The Home delivery query excluded subscriptions that were pending renewal since the fulfilment process executes before the renewal process.
By changing the query to include all HD subscriptions with autorenew=true we can generate the fulfilment file any number of days in advance without worrying about when the renewal takes place.
@paulbrown1982 @AWare @jacobwinch
> Hd query fix

- src/checker.js
- src/lib/storage.js
We forgot to update the fulfilment checker when we changed the fulfilment buckets. This explains why the check was now consistently failing every time instead of just sometimes.
I still think we could simplify the way it works but this is a starting point
@jacobwinch
> fix fulfilment check lambda

- cloudformation/cloudformation.yaml
Increase initial wait time for fulfilment Zuora queries. It is very unlikely that the query result will be available that fast, which triggers the whole retry logic too early. 
**We could also tweak:**
- Max retries: currently 10 
- Time between tries:currently 30 seconds
- BackoffRate:  currently 1.0 which means it will always wait the same between retries instead of increasing the wait as more retries fail
@jacobwinch @AWare @paulbrown1982
> increase initial wait time for Zuora Query response

- src/weekly/query.js
exclude rate plans that
-  are added in an amendment with acceptance date in the future 
- were removed in an amendment with effective date in the past
Note that this would fail if a rate plan is both added and removed in future amendments as it looks at only the last amendment.
@paulbrown1982
> Weekly query fix

- cloudformation/cloudformation.yaml
We are getting some timeouts on guardian weekly fulfilments on fridays. 
This will will make the step functions wait twice as long for Zuora queries to complete before giving up
> wait a little more time for Zuora to finish the queries

- src/weekly/query.js
The new GW products use different rate plan names for introductory periods (e.g. 6 for 6), so they aren't being picked up correctly by our queries.
> Recognise new 6 for 6 plans

- package.json
- yarn.lock
[https://app.snyk.io/vuln/npm:sshpk:20180409](https://app.snyk.io/vuln/npm:sshpk:20180409)
We need to upgrade request so that we aren't open to this vulnerability. 
I am unsure how to test this - all I can say so far is that `yarn test` doesn't yield any errors
> Upgrade request

- package.json
- yarn.lock
This PR addresses a [Snyk issue](https://app.snyk.io/org/the-guardian-cuu/project/12f9e7e2-65a9-463e-ab68-1083c21a6919/). 
Upgrades `request-promise-native` to a version that depends on tough-cookie 2.3.3 to resolve [Snyk issue](https://app.snyk.io/vuln/npm:tough-cookie:20170905).
> Snyk: bump request-promise-native

- yarn.lock
Snyk has 3 complains about request-promise-native
https://app.snyk.io/org/the-guardian-cuu/project/12f9e7e2-65a9-463e-ab68-1083c21a6919/
So I have done a `yarn upgrade request-promise-native` and it made these changes.
`yarn test` still seems to pass, so hopefully it's all happy!
@mario-galic @pvighi maybe you can give the once over and see if it looks like we need to do anything more detailed before merging please!
> update request-promise-native for synk

- cloudformation/cloudformation.yaml
This has been timing out recently. When I re-ran an execution the queries completed relatively soon after we gave up polling.
I don't think there's any harm in increasing the number of retries here.
> Extend polling period for FetchResults lambda

- src/weekly/query.js
Our new way of amending subscriptions for holiday stops makes the effective date of the holiday stop (when the credit is paid) the first day of the next billing period.  This means that the current query to find publications that shouldn't be delivered won't work; it uses the effective date as the threshold for finding holiday stops but obviously that will always be false in the future with the new method.
I think the logic of this should continue to work with existing manually applied stops.  Please let me know if this isn't true.  I've run a report on prod data and there are differences between the two data sets but only where it looks like a subscription is being included iin the current dataset when it shouldn't be there.
What I don't understand is why this query isn't filtered on GW …
> Use holiday start date as threshold for GW fulfilment suspension

- package.json
- yarn.lock
because of a snyk warning
Tested in CODE:
> Bump request-promise-native dependency

- src/homedelivery/query.js
**FIXME**: The second OR disjunct can be removed once `HolidayEnd__c` of the last old style holiday stop has passed:
```
((Subscription.Status = 'Active' OR Subscription.Status = 'Cancelled') AND
ProductRatePlanCharge.ProductType__c = 'Adjustment' AND
RateplanCharge.Name = 'Holiday Credit' AND
RatePlanCharge.EffectiveStartDate <= '${formattedDate}' AND
RatePlanCharge.HolidayEnd__c >= '${formattedDate}' AND
RatePlan.AmendmentType != 'RemoveProduct')
```
In the new world `EffectiveStartDate` indicates when the credit will be applied in the next invoice, **not** the holiday stop date.
Related Guardian Weekly PR: https://github.com/guardian/fulfilment-lambdas/pull/112
> Handle Home Delivery holiday stops not based on EffectiveStartDate

- README.md
as part of the work to improve our terminology, I have updated the default branch name. This PR makes sure any references in the repo are up to date.
I have been following the instructions here: https://docs.google.com/document/d/1nqC5Uk6n3y7S79m1yiG6oqT8NtXWpDcsS-uLI_RK7Mg/edit#
> update references to master to be main now

- src/homedelivery/query.js
Related PR: https://github.com/guardian/support-service-lambdas/pull/686
Zuora now has per-product holiday credit rate plans
whilst previously there was only one for all
```
DO NOT USE MANUALLY: Holiday credit - automated
```
which was hardcoded in the filter.
Query can be tested directly in postman, for example
```
POST /v1/batch-query/ HTTP/1.1
Host: rest.zuora.com
Accept: application/json
Content-Type: application/json
Authorization: Bearer ***************
{
"format" : "csv",
"version" : "1.0",
"name" : "mario-fulfilment_lambda_holidaysuspension-hd",
"encrypted" : "none",
"useQueryLabels" : "true",
"dateTimeUtc" : "true",
"queries" : [
{
"name" : "mario-fulfilment_lambda_holidaysuspension",
"query" : "SELECT Subscription.Name FROM rateplancharge WHERE ((Subscription.Status = 'Active' …
```
> Update RatePlan.Name filter of Home Delivery holiday suspensions

- src/homedelivery/query.js
Previously, the home-delivery holiday-stop query unnecessarily referred to discount rate plans by name.  This change removes that dependency.  It also removes an old query that is now redundant.  As a result the home-delivery query is identical to the GW query.  So a further step could be to share them.
1. I've set up reports for the query as it was and compared the results with an identical query without the discount rate-plan name.  The results for both are identical.
1. I've run a report for the old query to prove that it's now redundant as it has no results.
We should check a few holiday-stop files after this is merged to ensure there are still contents.
The change might stop holiday-stops being output and so they will be delivered in spite of the stop.  I propose to merge this next …
> Simplify home-delivery holiday-stop query

- cloudformation/cloudformation.yaml
We are seeing an alarm go off in Code because there aren't any Home Delivery subs in UAT Zuora.
This doesn't seem to be very useful.
> Only set alarms in Prod

- __tests__/lib/formatters.js
- src/homedelivery/export.js
- src/lib/formatters.js
* Addresses email `CSR bug report - case: 01710356`
* Salesforce [CSVReader.cls ](https://github.com/guardian/salesforce/blob/1841a6c6a64b638afef2916ca0b643dbbb7d8a6f/force-app/main/default/classes/CsvReader.cls) seems to get confused if a column value has double quotes followed by comma inside it `"",`
* Related PR: https://github.com/guardian/salesforce/pull/328
Unit test
```
yarn jest -t='should format delivery instructions for Salesforce CSV parser'
```
Check in Salesforce
```
SELECT id, Class_Name__c, CreatedDate, info__c 
FROM Apex_Error__c
WHERE Class_Name__c='DeliveryDocumentWrapper'
ORDER BY CreatedDate DESC
LIMIT 5
```
and subscription a2F0J000002jK6z.
Delivery records for a2F0J000002jK6z should be correctly populated including delivery address and delivery instructions.
* …
> Format delivery instructions for Salesforce CSV parser

- __tests__/lib/formatters.js
- src/lib/formatters.js
* Workaround for limitation in Salesforce CsvReader: [Clarify with tests current behaviour of CsvReader regarding quotes and commas #333](https://github.com/guardian/salesforce/pull/333)
* 
1. Added `",` combination in `Sold To` contact 
1. Execute CODE fulfilment step function
1. Compare CSV files before and after
- Currently we apply this transformation only on delivery instructions field. Theoretically this could happen on any field but it is unlikely. If it happens again on another field, we could look into expanding transformation across fields or indeed modifying Salesforce CSV parsers to handle `",` sequence within particular field.
- Note fast-csv also has out-of-the-box facility to transform rows https://c2fo.github.io/fast-csv/docs/formatting/examples#transforming-rows
> Replace all double quotes with single quotes in delivery instructions column

- __tests__/weekly/exporter.js
- src/weekly/export.js
* https://trello.com/c/IGKv1DCf/2046-missing-hong-kong-fulfilment
* It seems old HK fulfilment provider is no longer valid, and we need to switch to the one serving ROW
* In terms of implementation change, if an explicit country is not specified, then it defaults to ROW. 
* https://github.com/guardian/fulfilment-lambdas#validating-deployment-to-prod
* Tested both in CODE and PROD (with temporarily released branch) by comparing files before and after. The HK rows are now added to ROW file `fulfilments/Weekly_ROW/2021-02-19_WEEKLY.csv` and the existing records do not seem to be affected.
Successful fulfilment to HK subscribers.
* The change seems to affect only GW
* The change seems to affect only ROW file
* ROW file does not seem corrupt and has more records than before due to added HK …
> Rewire Hong Kong (HK) subscribers to Rest of the World (ROW) fulfilment file

- src/lib/config.js
- src/weekly/salesforce_uploader.js
* Related PR: https://github.com/guardian/fulfilment-lambdas/pull/153
* Since HK now goes to ROW, there will be nothing to upload to salesforce.
Run `weekly-fulfilmentUploader-CODE` lambda and check HK is not part of the output
```
[
{
"name": "GWNZ_19_02_2021_10022021_16.csv",
"id": ""
},
{
"name": "GWFR_19_02_2021_10022021_16.csv",
"id": ""
},
{
"name": "GWAU_19_02_2021_10022021_16.csv",
"id": ""
},
{
"name": "GWCA_19_02_2021_10022021_16.csv",
"id": ""
},
{
"name": "GWCA_HAND_19_02_2021_10022021_16.csv",
"id": ""
},
{
"name": "GWRW_19_02_2021_10022021_16.csv",
"id": ""
},
{
"name": "GWUK_19_02_2021_10022021_16.csv",
"id": ""
},
{
"name": "GWUS_19_02_2021_10022021_16.csv",
"id": ""
},
{
"name": "GWVA_19_02_2021_10022021_16.csv",
"id": ""
}
]
```
* There should be no risk given HK files …
> Do not upload HK fulfilment file to salesforce

- src/weekly/query.js
https://trello.com/c/93cyav3B/2037-erroneous-duplicates-in-fulfilment-files
The cause of the problem is adding (and removing) multiple subsequent products in advance, that is having the following sequence of amendments: 
```
Remove Product -> Add Product -> Renew -> Remove Product -> Add Product -> Renew -> ...
```
which results in multiple `Amendment.EffectiveDate` being satisfied by filter
```
Amendment.EffectiveDate > '${formattedDeliveryDate}'
``` 
due to 
| Subscription  | AmendmentType  | Amendment.EffectiveDate  | EffectiveStartDate |
| ------------- | ------------------ |  -------------------------- | ------------------ |
| A00000         | RemoveProduct     | 2021-03-29                         | 2020-03-29          |
| A00000         | RemoveProduct      | 2022-03-29 …
> Fix erroneous duplicate copies of Guardian Weekly in fulfilment files

- src/homedelivery/export.js
Removing the phone number from the Home Delivery fulfilment file as it's been confirmed that it is not used by the new delivery supplier, and it better respects customer privacy and reduces risk of an information security incident arising from a lost delivery manifest. The column needs to remain in the CSV file for compatibility, which supports blanks as phone numbers are already sparse.
Run the Lambda as per the instructions for tomorrow's file and confirm there are no phone numbers and the columns all align.
No phone numbers in the manifest.
CEX have confirmed with the Head of Supply Chain that this can and should be removed.
N/A
> Removing the phone number from the Home Delivery fulfilment file

- src/weekly/query.js
We were giving away up to two issues after cancellation but that was causing supply problems in some cases, as well as being wasteful.
This change reduces the fulfilment period following cancellation to a max of 6 days.
> Reduce fulfilment period for GW following cancellation

- src/weekly/query.js
There is a business rule that cancelled gift GW subs shouldn't be fulfilled even when the term end date falls within a future cutoff period.  This change to the fulfilment query reflects that rule.
Has been tested in the Code environment.
> Don't fulfil cancelled gift GW subs

- src/weekly/query.js
This follows on from #165 
but this time gift subs in a 'cancellation pending' state are fulfilled up to the date when they are cancelled.
So the difference between gift and non-gift subs is that non-gifts have a cut-off period where an issue will be fulfilled if the term of the sub ends between two publication dates.
> Don't fulfil cancelled GW gift subs (attempt 2)

- src/weekly/WeeklyExporter.js
- src/weekly/query.js
The purpose of this change is to indicate the value of deliveries at the EU border for VAT purposes.
This change adds new 'Unit price' and 'Currency' fields to the EU fulfilment file only.  The unit price is based on the [MRR](https://www.zuora.com/billing-topics/monthly-recurring-revenue-definition) value of the subscription.
For EU, header row looks like this:
`"Subscriber ID","Name","Company name","Address 1","Address 2","Address  3","Country","Post code","Copies","Unit price","Currency"`
Typical value row looks like this:
`"A-S12345678","kITbFBtqUoMmG9xAAyc kITbFBtqUoMmG9xAAyc","","kITbFBtqUoMmG9xAAyc","kITbFBtqUoMmG9xAAyc","kITbFBtqUoMmG9xAAyc","FRANCE","N19GU","1.0","4.71","EUR"`
Tested on Code.
See also:
* #170 
* https://trello.com/c/Xcr8mZ0k/2457-goal-adding-unit-prices-to-guardia …
> Append unit price field to GW EU fulfilment rows

- __tests__/weekly/exporter.js
- __tests__/weekly/salesforce_uploader.js
- src/lib/config.js
- src/weekly/WeeklyExporter.js
- src/weekly/export.js
- src/weekly/query.js
- src/weekly/salesforce_uploader.js
The purpose of this change is to enable us to add a value field for EU deliveries for VAT purposes.
This change adds a new fulfilment file to the list to be generated, specifically for deliveries to all EU countries.
This supersedes the fulfilment file for France, which will no longer be generated after this change.
The RoW file should be smaller as a result, as all other EU countries were previously written there.
For this change to work, a corresponding change is required to the stage-specific config files stored in S3. 
Tested on Code.
See:
https://trello.com/c/Xcr8mZ0k/2457-goal-adding-unit-prices-to-guardian-weekly-subscriber-file
> Generate fulfilment file for EU

- src/weekly/WeeklyExporter.js
- src/weekly/query.js
I found that when using the account monthly recurring revenue (MRR) it comes out as 0 for gift subs.
By using the rate plan charge MRR instead, all EU subs have a unit price.
The way that this MRR is calculated is explained [here](https://knowledgecenter.zuora.com/Billing/Subscriptions/Customer_Accounts/A_How_to_Manage_Customer_Accounts/E_Key_Metrics/B_Monthly_Recurring_Revenue).
The conversion of this to a unit value in this codebase hasn't changed.
In ZOQL, when you query for RatePlanCharge.MMR you get back in the result set these additional columns:
* RatePlanCharge.MRR
* RatePlanCharge.MRRHomeCurrency
* RatePlanCharge.MRRCurrencyRounding
* RatePlanCharge.ExchangeRate
* RatePlanCharge.ExchangeRateDate
* RatePlanCharge.ProviderExchangeRateDate
* RatePlanCharge.HomeCurrency
* …
> Use rate plan charge MRR, instead of account MRR, to calculate unit price of GW in EU

- src/weekly/WeeklyExporter.js
- src/weekly/query.js
This changes the value we put against each published issue delivered to addresses in the EU.
Previously, we were applying the actual value of each subscription, calculated from its MRR.  This caused problems because some are in GBP rather than EUR.  It was decided that a universal arbitrary value would do just as well as individual calculations.
Tested in Code.
> Apply a universal arbitrary value to Guardian Weeklies delivered to the EU

- src/homedelivery/query.js
This PR attempts to select rate plans more accurately based on whether they are likely to be auto renewed by zuora, in order to fulfil home delivery correctly.
We are seeing a problem where people who have had a price rise are appearing twice in the fulfilment file during the period where the fulfilment date was on or after the price rise date, but the fulfilment process was running on or before the price rise date.
For example, if someone's price rise was sat 9th july, the fulfilment runs for sat/sun/mon would be picked up on friday's run.  This means they would appear twice in those 3 files, and then return to once after that date.
The way price rise works is it creates an amendment in Zuora which will remove the current/cheaper charge sometime in the future, and adds the more expensive …
> make HD fulfilment query detect an auto renewing sub more easily

- README.md
- __tests__/resources/input/weekly/exporter.json
- src/weekly/WeeklyExporter.js
- src/weekly/export.js
We are moving any Guardian Weekly subscriptions with delivery country Japan, Thailand or Singapore to be in the Australia Guardian Weekly fulfilment file, and removing them from the Rest Of World fulfilment file.
**Why?**
This is due to our delivery partners struggling with deliveries to these countries due to restrictions in the Russian airspace. We hope moving these subscriptions to be handled by our delivery partners based in Australia works.
**Testing**
We have ran the `exporter.js` script in PROD, and confirm the produced CSV files are correct:
[CSV for AU](https://s3.console.aws.amazon.com/s3/object/fulfilment-export-prod?region=eu-west-1&prefix=fulfilments/Weekly_AU/2022-08-05_WEEKLY.csv)
[CSV for Rest Of World](https://s3.console.aws.amazon.com/s3/object/fulfilment-export-prod?regi …
> Move GW subs with delivery country Japan, Thailand or Singapore to be in the Australia fulfilment file

- .github/workflows/ci.yml
- package.json
This migrate the build of this repository software from Team City to GHA. 
The existing script is here: https://github.com/guardian/fulfilment-lambdas/blob/62c3893667f3ab39327b568b034c55ff01f6ecdd/build-tc.sh
Last build on Team City:
.
755 was the last build made by TC. After which I disabled the TC trigger. 774 was the first GHA build seen by Riff-Raff.
.
.
.
> migrate build from TC to GHA

- .github/workflows/ci.yml
When we did https://github.com/guardian/fulfilment-lambdas/pull/198 we used 
```
mv dist fulfilment-lambdas
zip -r fulfilment-lambdas.zip fulfilment-lambdas
```
Which caused the following surprising problem 
We correct that problem using an idea from here: https://github.com/guardian/email-mvt/blob/main/.github/workflows/email-mvt-archive-build.yml#L55 via @paulbrown1982 
to then become 
```
pushd dist
zip -r fulfilment-lambdas.zip ./*
popd
```
> better generation of artifact

- cloudformation/cloudformation.yaml
- riff-raff.yaml
- [Uses the generalised alarm-handler](https://github.com/guardian/support-service-lambdas/pull/2273)
- `App` tag was added manually as the cloud-formation deployment is "not quite finished"
> feat: report alarms to alarms-handler

- src/weekly/query.js
[Trello](https://trello.com/c/p5yORFGq/895-change-fulfilment-lambdas-to-look-for-product-type-on-charge)
This updates the query for the Guardian Weekly fulfilment.
We now look for `ProductRatePlanCharge.ProductType__c = 'Guardian Weekly'` rather than `Product.ProductType__c = 'Guardian Weekly'` since Guardian Weekly charges are nested in the new 3-tier subscriptions.
We have checked the output diffs on CODE and they look correct as the output with the new query contains all rows of the previous query plus the new subscriptions containing the new 3-tier products.
> feat: query ProductType__c in ProductRatePlanCharge to include GW nested in new 3-tier subscriptions

- __tests__/weekly/salesforce_uploader.ts
- cloudformation/cloudformation.yaml
- package.json
- src/weekly_salesforce_uploader.ts
This fixes a bug introduced during the conversion of the build process from JavaScript to TypeScript.
The project has 7 lambda handlers. Six of them are in the root `src` folder. One of them (the one failing) was inside the `weekly` folder, which was not picked up by the `package` script.
The solution I went for is to move that handler to the root, for consistency.
> fix: have all handlers at the root of the src folder

- cloudformation/cloudformation.yaml
[Trello](https://trello.com/c/axAyxmPb/344-aws-fsbp-high-vulnerabilities-s3-general-purpose-buckets-should-block-public-access)
S3 general purpose buckets should block public access.
This is part of new obligations for fixing AWS vulnerabilities.
See [document](https://docs.google.com/document/d/1Q_ts5mbRvASCGo3UfsPHwUVvSXc3f2fkK2Fwp6N9Pxc/edit?tab=t.0#heading=h.64oh0k2bzslf) for more details.
Before:
After deploying the branch to CODE:
> infra: block public access for general purpose S3 buckets
